### ISSUE TITLE
Conv2DSum layer error

### ISSUE THREAD

**Issue by yannickl96** [pronobis/libspn-keras#23]
Hello,

I am currently trying to apply Conv2DSum layers and get the following error:
``AttributeError: 'Conv2DSum' object has no attribute '_forward_normalize'``
All I did was replace the Local2DSum layers from the architecture in #22 with Conv2DSum layers as the only difference is that the weights are now shared if I understood correctly.

Any help is greatly appreciated!
Cheers,
Yannick

**Comment by jostosh** [comment]
Thanks for pointing it out. Fix is on its way. Will release `0.5.1` once its merged and ready.
