### ISSUE TITLE
Generator Example

### ISSUE THREAD

**Issue by S1mmy** [pronobis/libspn-keras#28]
I would like to see an example to generate images, like it was a GAN.

For example for MNIST.

**Comment by jostosh** [comment]
Hi S1mmy, thanks for the suggestion! I will try to prepare one in the next few days.

**Comment by S1mmy** [comment]
Hey Jostosh, thank you, for your fast answer!

Tomorrow i have to hold a little presentation, would it be possible to send me some code, so i can generate some images? 😅

That would be really awesome! ( My mail adress is: sammy-it@web.de )

Thanks for your support!

**Comment by jostosh** [comment]
Sampling wasn't yet properly supported by the library. I'm almost there, but cannot promise anything yet. If it is of any help, the paper on [Einsum Networks](https://arxiv.org/abs/2004.06231) (which are just SPNs) shows some images of samples drawn from an SPN.

I cannot yet also claim anything about the quality of the samples, they might not be as impressive as what you expect from a GAN.

**Comment by S1mmy** [comment]
Okay, thank you very much for your support!
That helps a lot.

Then I'll wait, till you updated the library and check it out! 😊

**Comment by jostosh** [comment]
Just released `v0.6.0` of the library that includes everything needed for [this example](https://colab.research.google.com/github/pronobis/libspn-keras/blob/master/examples/notebooks/Sampling%20with%20conv%20SPNs.ipynb) on sampling.
