### ISSUE TITLE
 Generative learning for continuous MNIST data using randomly structured SPNs

### ISSUE THREAD

**Issue by S1mmy** [pronobis/libspn-keras#29]
I was wondering if you could give an example of how to do this like in the old library: https://github.com/pronobis/libspn/blob/master/ipynb/mnist_continuous_hard_em.ipynb

Unfortunately the output in the old library is empty for me.

**Comment by jostosh** [comment]
Hi S1mmy, I'm currently working on putting in a notebook example with generative learning with sampling. That example would cover continuous variables and generative learning. Is there something else in the old library example you'd like to be included?

**Comment by S1mmy** [comment]
No, that's all, thank you.

**Comment by jostosh** [comment]
Just released v0.6.0 of the library that includes everything needed for [this example](https://colab.research.google.com/github/pronobis/libspn-keras/blob/master/examples/notebooks/Sampling%20with%20conv%20SPNs.ipynb) on sampling and continuous variables.
