### ISSUE TITLE
simple.py

### ISSUE THREAD

**Issue by anicolson** [pronobis/libspn-keras#4]
Hi, with simple.py:

  File "libspn_keras_example.py", line 9, in <module>
    from libspn_keras.models import build_ratspn
ImportError: cannot import name 'build_ratspn'.

**Comment by jostosh** [comment]
Hi Aaron, thanks for reporting this. The `simple.py` script was untouched for a while and actually didn't incorporate some of the breaking changes. I will have to fix that. The script was also not doing that much, so I might actually remove it altogether. What would you like to do with it?

**Comment by anicolson** [comment]
I was just letting you know 🙂. I was just going through the examples to start learning libspn-keras.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
